-- Dodaj dodatkowe kolumny do tabeli contracts dla pełnych danych umowy
ALTER TABLE public.contracts
ADD COLUMN IF NOT EXISTS company_name TEXT,
ADD COLUMN IF NOT EXISTS company_email TEXT,
ADD COLUMN IF NOT EXISTS company_phone1 TEXT,
ADD COLUMN IF NOT EXISTS company_phone2 TEXT,
ADD COLUMN IF NOT EXISTS lessor_name TEXT,
ADD COLUMN IF NOT EXISTS lessor_address TEXT,
ADD COLUMN IF NOT EXISTS lessor_phone TEXT,
ADD COLUMN IF NOT EXISTS lessor_website TEXT,
ADD COLUMN IF NOT EXISTS lessor_email TEXT,
ADD COLUMN IF NOT EXISTS rental_location TEXT,
ADD COLUMN IF NOT EXISTS return_by TEXT,
ADD COLUMN IF NOT EXISTS tenant_name TEXT,
ADD COLUMN IF NOT EXISTS tenant_email TEXT,
ADD COLUMN IF NOT EXISTS tenant_phone TEXT,
ADD COLUMN IF NOT EXISTS tenant_address TEXT,
ADD COLUMN IF NOT EXISTS tenant_id_type TEXT,
ADD COLUMN IF NOT EXISTS tenant_id_number TEXT,
ADD COLUMN IF NOT EXISTS tenant_id_issuer TEXT,
ADD COLUMN IF NOT EXISTS tenant_pesel TEXT,
ADD COLUMN IF NOT EXISTS tenant_nip TEXT,
ADD COLUMN IF NOT EXISTS tenant_license_number TEXT,
ADD COLUMN IF NOT EXISTS tenant_license_date DATE,
ADD COLUMN IF NOT EXISTS vehicle_vin TEXT,
ADD COLUMN IF NOT EXISTS vehicle_next_inspection DATE,
ADD COLUMN IF NOT EXISTS vehicle_insurance_number TEXT,
ADD COLUMN IF NOT EXISTS vehicle_insurance_valid_until DATE,
ADD COLUMN IF NOT EXISTS vehicle_additional_info TEXT,
ADD COLUMN IF NOT EXISTS additional_drivers JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS payments JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS notes TEXT;